/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RfCountries {
    }
    interface RfSkeleton {
    }
}
declare global {
    interface HTMLRfCountriesElement extends Components.RfCountries, HTMLStencilElement {
    }
    var HTMLRfCountriesElement: {
        prototype: HTMLRfCountriesElement;
        new (): HTMLRfCountriesElement;
    };
    interface HTMLRfSkeletonElement extends Components.RfSkeleton, HTMLStencilElement {
    }
    var HTMLRfSkeletonElement: {
        prototype: HTMLRfSkeletonElement;
        new (): HTMLRfSkeletonElement;
    };
    interface HTMLElementTagNameMap {
        "rf-countries": HTMLRfCountriesElement;
        "rf-skeleton": HTMLRfSkeletonElement;
    }
}
declare namespace LocalJSX {
    interface RfCountries {
    }
    interface RfSkeleton {
    }
    interface IntrinsicElements {
        "rf-countries": RfCountries;
        "rf-skeleton": RfSkeleton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rf-countries": LocalJSX.RfCountries & JSXBase.HTMLAttributes<HTMLRfCountriesElement>;
            "rf-skeleton": LocalJSX.RfSkeleton & JSXBase.HTMLAttributes<HTMLRfSkeletonElement>;
        }
    }
}
